import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@mantine/core/styles.css";
import "@mantine/notifications/styles.css";
import "@mantine/dates/styles.css";

import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import { Header } from "../components/shared/Header";
import { Footer } from "../components/shared/Footer";
import { ClientProviders } from "../components/ClientProviders";
import { NavigationProgress } from "@mantine/nprogress";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next App With OIDC Authentication",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={inter.className}>
        <MantineProvider>
          <NavigationProgress />
          <ClientProviders>
            <Header />
            {children}
            <Footer />
          </ClientProviders>
        </MantineProvider>
      </body>
    </html>
  );
}
